export default {
  // AUTH ACTION TYPES
  SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
  SET_USER: 'SET_USER',
  CLEAR_AUTH: 'CLEAR_AUTH',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  REGISTER_USER: 'REGISTER_USER',
  // EVENT ACTION TYPES
  SET_EVENTS: 'SET_EVENTS',
  CREATE_EVENT: 'CREATE_EVENT',
  FETCH_EVENTS: 'FETCH_EVENTS',
  CLEAR_EVENTS: 'CLEAR_EVENTS',
  ADD_EVENT: 'ADD_EVENT',
  // BOOKING ACTION TYPES
  FETCH_BOOKINGS: 'FETCH_BOOKINGS',
  SET_BOOKINGS: 'SET_BOOKINGS',
  BOOK_EVENT: 'BOOK_EVENT',
  CANCEL_BOOKING: 'CANCEL_BOOKING',
  DELETE_BOOKING: 'DELETE_BOOKING',
  ADD_BOOKING: 'ADD_BOOKING'
}
